### ISSUE TITLE
Files in examples/pdf_store_and_query_with_chroma.rb don't exist

### ISSUE THREAD

**Issue by technicalpickles** [patterns-ai-core/langchainrb#153]
I was looking over these, and noticed:

https://github.com/andreibondarev/langchainrb/blob/eecd114a655e5f1b51ebcd9d39e26e72cfb918f6/examples/pdf_store_and_query_with_chroma.rb#L22-L24

These files don't exist. I'm not sure if the intent is to run them from where it's located or not. If it's not, then should at least include some comments to the effect of changing the file paths. I think it would be reasonable for them to live in the repository though.

**Comment by andreibondarev** [comment]
@technicalpickles Think we should use the ones in `spec/fixtures/loaders/` instead? They're not the "best" example files, maybe we should find ones that really showcase the capabilities of using this gem.
