### ISSUE TITLE
Weather questions sometimes blows up on certain city names

### ISSUE THREAD

**Issue by mattlindsey** [patterns-ai-core/langchainrb#175]
ChainOfThought agent usually provides a good city name to the Weather tool, but can blow up (or be tricked into blowing up) on city names.

First example works, second blows up on same city:

<img width="1023" alt="image" src="https://github.com/andreibondarev/langchainrb/assets/5638339/fa200803-8dbd-42c7-9d4f-92dc6cb67db7">

**Comment by andreibondarev** [comment]
I think this issue is either on the gem's or the actual API's end. "Boston, MA" is a completely valid way of formatting the location name. For example: If I type it in on weather.com -- I won't be getting an error.

**Comment by mattlindsey** [comment]
I think this is because there are two ways listed in the README for the gem to get weather for a city.  
We are currently using the first one below.  Using the second method may solve the problem, but it needs a little research.

```ruby
data = client.current_weather(city: 'London')

client.current_city('New York', 'NY', 'US')

**Comment by andreibondarev** [comment]
This issue is definitely fixed now.
