### ISSUE TITLE
Issue with SQLQueryAgent maximum context length

### ISSUE THREAD

**Issue by qubitam** [patterns-ai-core/langchainrb#187]
I have been getting this issue when I try to execyte the sql query agent : 
`This model's maximum context length is 4097 tokens, but the given text is 7635 tokens long. (Langchain::Utils::TokenLength::TokenLimitExceeded)`

the code is as below : 
`

        database = Langchain::Tool::Database.new(connection_string: "postgres://qubitam:@localhost:5432/unipharm_development")

        agent = Langchain::Agent::SQLQueryAgent.new(llm: Langchain::LLM::OpenAI.new(api_key: ENV["OPENAI_API_KEY"]), db: database)
        agent.run(question: "#{self.content}")`

**Comment by andreibondarev** [comment]
@qubitam, @mattlindsey fixed it. Could you please give it a try again?

When initializing the `SQLQueryAgent`, pass a list of `tables: []` (tables that should be used in the query) or `except_tables: []` (tables that should not be used in the query).

But we're still going to work on a better fix, one that does not require actually listing out your tables.
