### ISSUE TITLE
Don't limit HTML processor to certain tags

### ISSUE THREAD

**Issue by drale2k** [patterns-ai-core/langchainrb#319]
The HTML processor is currently limited to only extract text from `h1 h2 h3 h4 h5 h6 p`. Given a HTML page this will miss a lot of content like divs, article, list and table tags. 

Would it not be better to just extract all text by passing the contents of `<body>` to Nokogiri, like `Nokogiri::HTML(data).text`

**Comment by andreibondarev** [comment]
@drale2k It does depend on how you'd like to chunk the document. Like does put an <h1>Article Title</h1> into a separate chunk on its own make sense?
