### ISSUE TITLE
Support more loaders

### ISSUE THREAD

**Issue by drale2k** [patterns-ai-core/langchainrb#323]
It would be great to support more content loaders, such as:

- Youtube video transcripts
- Direct Website crawling and via Sitemaps
- Google Drive folders 

I stumbled upon [embedchain](https://github.com/embedchain/embedchain) which looks really nice. I think it can act as a great reference

**Comment by andreibondarev** [comment]
@drale2k I'm currently overhauling all of the loaders and chunkers and will keep you updated.

**Comment by basicfeatures** [comment]
Could you please include Shell and Filesystem too?

Although can't Shell just use the default shell? Personally I use OpenBSD's hardened ksh, but for my scripts I prefer zsh as opposed to the overcomplicated and advisory prone bash ([check out this mess followed by a cleanup](https://gist.github.com/basicfeatures/3d28e07481e65155b81c627b38471023)).
