### ISSUE TITLE
Integrate SQLite and sqlite-vss extension as another vectorsearch provider

### ISSUE THREAD

**Issue by andreibondarev** [patterns-ai-core/langchainrb#349]

**Comment by itsderek23** [comment]
Looks like there are 7 providers ... does it make sense to close this for now as 7 feels like enough to support for an eventual 1.0 release?

**Comment by aquaflamingo** [comment]
Curious if there was any more thought on this? SQLite is growing in support from the Ruby and Rails community at the moment with the new Rails 8 "Solid" [approach](https://rubyonrails.org/2024/9/27/rails-8-beta1-no-paas-required).

There's been some sponsored work from Mozilla and others with [sqlite-vec](https://github.com/asg017/sqlite-vec) to enhance SQLite in that way. 

Thanks for the great gem!

**Comment by CarlQLange** [comment]
I have added [a PR with some support for sqlite-vec](https://github.com/patterns-ai-core/langchainrb/pull/906) with the caveat that I don't know what I'm doing - all I know is, works on my machine :)

**Comment by CarlQLange** [comment]
Related sister PR in langchainrb-rails: https://github.com/patterns-ai-core/langchainrb_rails/pull/133
