### ISSUE TITLE
Support for Vertex AI

### ISSUE THREAD

**Issue by palladius** [patterns-ai-core/langchainrb#397]
Andrei, as a Ruby fan and Googler, I'd like to contribute for Vertex AI. 
Please guide me through this as my code might not meet your qulity gates :)

I'm going to file a PR with JUST the code for Embeddings as I got to work (!).
there's plenty of work to merge it but I want to show you some code anyway.

Working code for Vertex AI can be found here: https://github.com/palladius/genai-googlecloud-scripts/tree/main/06-ruby-text-code-embeddings-images

**Comment by andreibondarev** [comment]
Addressed in https://github.com/patterns-ai-core/langchainrb/pull/402.
