### ISSUE TITLE
Support for skipping OpenAI token limit validation during vLLM-Langchain integrations

### ISSUE THREAD

**Issue by alexzfan** [patterns-ai-core/langchainrb#400]
vLLM offers an OpenAI-like inference server endpoint that allows it to be dropped into applications that currently use the OpenAI Protocol. This has been integrated into the python langchain package (https://python.langchain.com/docs/integrations/llms/vllm), but not the ruby gem. Hacking around it by using the base OpenAI constructor such as below leads to token length/limit validation errors

```
Langchain::LLM::OpenAI.new(
    api_key: "EMPTY",
    llm_options: {
        uri_base: "https://localhost:8000/v1/",
        extra_headers: {
             "Content-Type": "application/json",
         },
    default_options: {
         temperature: 0.2,
         chat_completion_model_name: "tiiuae/falcon-7b"
    }
)
```

Is there any plans to integrate this fully or has anyone been able to find a different solution to this?

**Comment by leenyburger** [comment]
Yup, I'm also having this issue when trying to implement the Perplexity API. @alexzfan did you already write a PR for this?

**Comment by andreibondarev** [comment]
We got rid of the max_token validation a while back so I'm closing this ticket.
