### ISSUE TITLE
Allowing more LLM models for Langchain::Assistance

### ISSUE THREAD

**Issue by mengqing** [patterns-ai-core/langchainrb#514]
Currently it only supports OpenAI, and I can see that there's a PR for supporting Gemini https://github.com/andreibondarev/langchainrb/pull/513

Is it better to make it more generic and make it extendable? Eg: be able to just extend a new LLM model without hard coding if conditions in the base class.

A lot of other LLM uses OpenAI standard specifications

**Comment by andreibondarev** [comment]
@mengqing Yes, I agree with you. It's best kept to be as generic as possible. Do you have any specific ideas/changes to propose? The current Gemini PR is a rough draft before I've thought about any abstractions at all. I've been thinking about maybe implementing a base/parent class and child classes that override specific methods, constants, etc.

**Comment by andreibondarev** [comment]
@mengqing Do you have any thoughts on how it's been implemented thus far?

**Comment by andreibondarev** [comment]
@mengqing Please open a new Issue if you'd like to see Langchain::Assistant support other LLMs.
