### ISSUE TITLE
Improve the Langchainrb documentation

### ISSUE THREAD

**Issue by andreibondarev** [patterns-ai-core/langchainrb#54]
### Problem
We have outgrown the single-file README. It is time to migrate to a more scalable solution.

Auto-generated documention RDoc-style may not be ideal as it'll read as a dry technical manual.

### Ideas
- Create a dedicated a website (@rickychilcott shared https://www.phlex.fun/ as an example)

**Comment by andreibondarev** [comment]
@ZhenhangTung I know you had mentioned that the documentation was lacking. Would [this](https://github.com/andreibondarev/langchainrb/wiki) be a better approach? Do you have any feedback on how to improve it further?

**Comment by ZhenhangTung** [comment]
@andreibondarev I do think it's better than the previous one. It's more structured and guide uses with concepts and code. I'll provide feedback if I have any in the future. For now, I believe we should prioritize something like user investigations or feature implementations.

**Comment by technicalpickles** [comment]
> Move documentation to Wiki

The main downsides are that you can't do PRs against them, and that they are totally separate from the main repo. That means it's an extra step to update if code changes means docs changes.

> Auto-generated documention RDoc-style may not be ideal as it'll read as a dry technical manual.

There is definitely value in it though. I've had to go to the langchain(.py) docs, and found them hard to read, and not super useful. Example: https://python.langchain.com/en/latest/reference/modules/vectorstores.html

Rails itself is a good example of thorough API reference (https://api.rubyonrails.org) , while there is still room for more general guides (https://guides.rubyonrails.org/)

**Comment by andreibondarev** [comment]
> https://python.langchain.com/en/latest/reference/modules/vectorstores.html
Yeah, that's exactly the technical manual look and feel that I was referring to.

I really like how Rails is documented. And not just the docs but the code itself!

And you're right, I think we'll need to create a `/docs` directory with a bunch markdown files so they can be modified along with actual code changes. And then auto-deploy the docs to Github Pages or something.

**Comment by technicalpickles** [comment]
A few changes landed since last update: https://github.com/andreibondarev/langchainrb/pull/112  https://github.com/andreibondarev/langchainrb/pull/152

https://rubydoc.info/gems/langchainrb now contains nearly all of the contents of the wiki, but located on the relevant class's rdoc.
