### ISSUE TITLE
Create `Langchain::Tool::Tavily` that uses Tavily service to do search.

### ISSUE THREAD

**Issue by andreibondarev** [patterns-ai-core/langchainrb#542]
### Description
The current search Tool utilizes the `google_search_results` gem which is a [very wonky experience](https://github.com/andreibondarev/langchainrb/blob/main/lib/langchain/tool/google_search/google_search.rb#L52-L127). We'd like to use something cleaner. What's been proposed was using Tavily AI.

### Tasks
- Integrate `Langchain::Tool::Tavily` as a tool into the project.

**Comment by andreibondarev** [comment]
I believe @bricolage is going to work on this one.

**Comment by swombat** [comment]
+1 that this is interesting to me. Is it still being worked on?

**Comment by andreibondarev** [comment]
> +1 that this is interesting to me. Is it still being worked on?

Yep, just shipped it!
