### ISSUE TITLE
Help: Example on how to use the assistant with Vector DB ?

### ISSUE THREAD

**Issue by pedroresende** [patterns-ai-core/langchainrb#557]
It would be great to have an example on how we can integrate an assistant with a RAG. 
Even though the documentation mentions that "Assistants can be configured with an LLM of your choice (currently only OpenAI), any vector search database and easily extended with additional tools." (https://github.com/andreibondarev/langchainrb/blob/main/lib/langchain/assistants/assistant.rb#L5)  there is no simple example on how we can do it

**Comment by andreibondarev** [comment]
@pedroresende I created a tool that wraps any vector search database. Take a glance at the diff here: https://github.com/andreibondarev/langchainrb/compare/add-vectorsearch-wrapper-tool?expand=1. I would **really** love your feedback on the approach.

This is how I tested it out:
```ruby
# This could be any LLM. It'll be used to embed documents and query.
llm = Langchain::LLM::Ollama.new url: ENV['OLLAMA_URL']

# Initialize the vectorsearch db
chroma = Langchain::Vectorsearch::Chroma.new(url: ENV["CHROMA_URL"], index_name: "docs", llm: llm)

# Add documents to it
chroma.create_default_schema
chroma.add_data paths: [
  # I imported this file: https://www.coned.com/-/media/files/coned/documents/small-medium-large-businesses/gasyellowbook.pdf
  Langchain.root.join("./file1.pdf"),
  Langchain.root.join("./file2.pdf"),
]

# Initialize the tool that will be passed to the Assistant
vectorsearch_tool = Langchain::Tool::Vectorsearch.new(vectorsearch: chroma)

# Initialize the Assistant
assistant = Langchain::Assistant.new(
  llm: Langchain::LLM::OpenAI.new(api_key: ENV['OPENAI_API_KEY']),
  thread: Langchain::Thread.new,
  instructions: "You are a chat bot that helps users find information from the Con Edison Yellow Book that you have stored in your vector search database. Feel free to refer to it when answering questions.",
  tools: [
    vectorsearch
  ]
)

# Ask away!
assistant.add_message_and_run content: "...", auto_tool_execution: true
```

**Comment by andreibondarev** [comment]
> @andreibondarev it worked perfectly fine, thanks for the help. The only strange thing that occurs, sometimes it's the following error
> 
> ![image](https://private-user-images.githubusercontent.com/951377/320064283-c9ac6663-a854-4781-81cd-2dec89135987.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMzMzMjYsIm5iZiI6MTcxMjMzMzAyNiwicGF0aCI6Ii85NTEzNzcvMzIwMDY0MjgzLWM5YWM2NjYzLWE4NTQtNDc4MS04MWNkLTJkZWM4OTEzNTk4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQxNjAzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMGU1ODFiNjUyZWQwMjZmMTk0ZmQ1MmVlY2E5ODFlMzFlM2E3YmMwZWZkZTNkYTc5ZjZhN2YyZGIxOTJiMjM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ix4hI7eo26dav4uVJ0UxzgsRJmlSZ4dIiUYnOLcrW8A)

I called the tool `Langchain::Tool::Vectorsearch`.

**Comment by pedroresende** [comment]
I know you did, I've renamed it to try to debug if it was clashing for some reason but I'm getting exactly the same error

**Comment by andreibondarev** [comment]
> I know you did, I've renamed it to try to debug if it was clashing for some reason but I'm getting exactly the same error

Make sure to modify the `NAME` constant as well:
```ruby
module Langchain::Tool
  class Vectorsearchtool < Base
    NAME = "vectorsearchtool"

```

**Comment by pedroresende** [comment]
> > I know you did, I've renamed it to try to debug if it was clashing for some reason but I'm getting exactly the same error
> 
> Make sure to modify the `NAME` constant as well:
> 
> ```ruby
> module Langchain::Tool
>   class Vectorsearchtool < Base
>     NAME = "vectorsearchtool"
> ```

Sure thing

**Comment by andreibondarev** [comment]
Resolved.

**Comment by Jellyfishboy** [comment]
This currently does not work.

If I use `.ask` it will return a relevant response.

If I use the Vectorsearch tool inside an assistant, it just tells me it can't find the relevant information.

**Comment by andreibondarev** [comment]
@Jellyfishboy Could you please show me how you were using the `Langchain::Tool::Vectorsearch` tool?

**Comment by mengqing** [comment]
@andreibondarev Is it possible to indicate which vector db to search for if I have multiple indices and I want to switch based on context?

**Comment by andreibondarev** [comment]
@mengqing You may need to create your own tool that is similar to https://github.com/patterns-ai-core/langchainrb/tree/main/lib/langchain/tool/vectorsearch.

There's no issue with doing something like:
```ruby
assistant = Langchain::Assistant.new(
   tools: [
     Langchain::Tool::Vectorsearch.new(vectorsearch: Langchain::Vectorsearch::Chroma.new(index_name: "private_documents"),
     Langchain::Tool::Vectorsearch.new(vectorsearch: Langchain::Vectorsearch::Chroma.new(index_name: "public_documents"),
   ]
```

But you need to override the [tool definitions](https://github.com/patterns-ai-core/langchainrb/blob/main/lib/langchain/tool/vectorsearch/vectorsearch.json) that are being passed to the LLM because they should not be identical.

**Comment by mengqing** [comment]
> @mengqing You may need to create your own tool that is similar to https://github.com/patterns-ai-core/langchainrb/tree/main/lib/langchain/tool/vectorsearch.
> 
> There's no issue with doing something like:
> 
> ```ruby
> assistant = Langchain::Assistant.new(
>    ...
>    tools: [
>      Langchain::Tool::Vectorsearch.new(vectorsearch: Langchain::Vectorsearch::Chroma.new(index_name: "private_documents"),
>      Langchain::Tool::Vectorsearch.new(vectorsearch: Langchain::Vectorsearch::Chroma.new(index_name: "public_documents"),
>    ]
> ```
> 
> But you need to override the [tool definitions](https://github.com/patterns-ai-core/langchainrb/blob/main/lib/langchain/tool/vectorsearch/vectorsearch.json) that are being passed to the LLM because they should not be identical.

Thanks, that's also what I was thinking in mind. Although I'm not sure how will LLM going to decide what vector db to use. Is this determined by the name and description defined in the definition file?

**Comment by andreibondarev** [comment]
@mengqing Yes, the name and description are sent to the LLM and it uses those as context.
