### ISSUE TITLE
Add support for Groq LLM

### ISSUE THREAD

**Issue by andreibondarev** [patterns-ai-core/langchainrb#565]

**Comment by mattlindsey** [comment]
I'll give it a try. This might already work using Langchain::LLM::OpenAI since the Groq technical FAQ says:

> How to transition from OpenAI to Groq? 
> It's incredibly simple to transition! If you have an application already using OpenAI's API, all it takes is updating 3 variables: the API key, the endpoint, and the model!

**Comment by andreibondarev** [comment]
@mattlindsey There's no way they're hosting OpenAI models, because other than GPT-2 none of them are open source. Only open-source ones: https://console.groq.com/docs/models.

**Comment by mattlindsey** [comment]
Actually the above example seems to work great with this:
  class OpenAI < Base
    DEFAULTS = {
      n: 1,
      temperature: 0.0,
      chat_completion_model_name: "llama3-8b-8192",
      embeddings_model_name: "text-embedding-3-small"
    }.freeze

So it should work by fixing something.

**Comment by mattlindsey** [comment]
@andreibondarev I take that back.  It seems to be working fully now as-is.  Maybe I just needed to wait for the Groq key to 'activate.'

**Comment by andreibondarev** [comment]
@mattlindsey I don't think it's a good idea. It would be kind of odd to instantiate an `LLM::OpenAI` class and then interface with `mixtral` model via Groq.

**Comment by mattlindsey** [comment]
@andreibondarev That seem to be what they tell you to do in their FAQ, and it works (with a fix, it seems).  But maybe you'd prefer a Groq LLM class.

**Comment by mattlindsey** [comment]
I discovered using parameters as follows works currently, in case anyone needs it now:

```ruby
llm = Langchain::LLM::OpenAI.new(api_key: 'your_groq_key_here', llm_options: { uri_base: 'https:/
/api.groq.com/openai/'})

llm.chat(messages: [{role: "user", content: "Tell me a story?"}], model: 'mixtral-8x7b-32768').completion
```

**Comment by drnic** [comment]
For now (for chat completion) it seems Groq Cloud is matching OpenAI's API. So the Groq adapter could use the underlying ruby-openai for the subset of API features currently available on https://api.groq.com/v1/openai

The [`test/fixtures/vcr_cassettes`](https://github.com/drnic/groq-ruby/tree/develop/test/fixtures/vcr_cassettes) folder of [groq-ruby](https://github.com/drnic/groq-ruby) should give some examples of API calls that are available.

Currently it is:

* https://api.groq.com/openai/v1/models
* https://api.groq.com/openai/v1/chat/completions

**Comment by mattlindsey** [comment]
@andreibondarev The following should work pretty easily, and I can do a PR if you want:
```ruby
module Langchain::LLM
  # LLM interface for Groq OpenAI compatible services
  #
  # Usage:
  #    groq = Langchain::LLM::GroqOpenAI.new(
  #      api_key: ENV["GROQ_API_KEY"],
  #      llm_options: {},
  #      default_options: {}
  #    )
  class GroqOpenAI < OpenAI
  ```

**Comment by drnic** [comment]
For anyone else who just wants a quick Groq solution who might not know where the diff defaults/overrides go (e.g. me) this seems to work:

```ruby
  @groq = llm = Langchain::LLM::OpenAI.new(
    api_key: ENV["GROQ_API_KEY"],
    llm_options: {
      uri_base: "https://api.groq.com/openai/"
    },
    default_options: {
      chat_completion_model_name: "llama3-70b-8192"
    }
  )

  messages = [{:role=>"system", :content=>"I like to solve maths problems."}, {"role"=>"user", "content"=>"What is 2+2?"}]
  @groq.chat(messages:).completion
  # => "That's an easy one! The answer is... 4!"
```

**Comment by llenodo** [comment]
@andreibondarev taking a look at this given the deepseek release, we're evaluating groq

groq is intended to be openai api compatible - https://console.groq.com/docs/openai - so I think some of these changes could make sense? 

_"We designed Groq API to be mostly compatible with OpenAI's client libraries, making it easy to configure your existing applications to run on Groq and try our inference speed."_

Are you open to revisiting or do you still prefer dedicated Groq class?

**Comment by drnic** [comment]
I’ve been using groq api for a year and I don’t use my own groq library. I always use generic OpenAI libraries, and so far so good.
