### ISSUE TITLE
Add a lean state machine for Assistant's phases.

### ISSUE THREAD

**Issue by andreibondarev** [patterns-ai-core/langchainrb#566]
## Description

The state machine should support the different states that the Assistant goes through. The [OpenAI Assistants one](https://platform.openai.com/docs/assistants/how-it-works/runs-and-run-steps) is a good inspiration and first step but need to be cautious to make it generic enough to account for other LLMs and workflows.

**Comment by dghirardo** [comment]
Hi @andreibondarev! I'm currently working on this task. You can assign it to me.

**Comment by andreibondarev** [comment]
> Hi @andreibondarev! I'm currently working on this task. You can assign it to me.

I'm curious whether you think we should be using a library here, and which one.

**Comment by andreibondarev** [comment]
Complete.
