### ISSUE TITLE
OpenAI add_texts not respecting dimension size

### ISSUE THREAD

**Issue by prdanelli** [patterns-ai-core/langchainrb#572]
It seems that recent work to allow the dimension size to be passed to the `embed` method means that we cannot use the current `add_texts` [method](https://github.com/patterns-ai-core/langchainrb/blob/main/lib/langchain/vectorsearch/qdrant.rb#L53), as it doesn't pass the `dimensions` keyword param. 

This means that we get back incompatable vectors (1536) from OpenAI, where the we need 512.

**Comment by andreibondarev** [comment]
@prdanelli That was definitely an omission and I'm sorry for going back and forth on it so much! 

I would suggest the following change:
```ruby
dimensions: @defaults[:dimensions]
```
here: https://github.com/patterns-ai-core/langchainrb/blob/main/lib/langchain/llm/openai.rb#L57

What do you think?

We also need to make sure that the rest of the LLM classes adhere to this interface as well.

**Comment by prdanelli** [comment]
@andreibondarev im genuinely really grateful for the work you put into this tool. We're using it in production at work and its a massive time saver. So thank you very much. 

I think the change you suggested should be good.

**Comment by prdanelli** [comment]
I'm just knocking up a PR now :)

**Comment by prdanelli** [comment]
PR added here: https://github.com/patterns-ai-core/langchainrb/pull/574
