### ISSUE TITLE
Rename `dimension:` parameter to `dimensions:` everywhere.

### ISSUE THREAD

**Issue by andreibondarev** [patterns-ai-core/langchainrb#575]
## Description
"Dimensions" (plural) is clearer than "dimension". The reference is to the depth of the array, the number of dimensions in a vector.

## Tasks
1. Rename the `dimension:` parameter to `dimensions:` everywhere. Example: https://github.com/patterns-ai-core/langchainrb/blob/main/lib/langchain/llm/cohere.rb#L18

**Comment by prdanelli** [comment]
This will likely be a breaking change so should be highlighted in any change docs released :)
