### ISSUE TITLE
When calling the 'summarize' function in ollama, it's not possible to specify the mode

### ISSUE THREAD

**Issue by lukefan** [patterns-ai-core/langchainrb#576]
When calling the 'summarize' function in ollama, it's not possible to specify the model; 
the default model specification is also largely ineffective. 
I hope more examples of ollama can be provided.

**Comment by andreibondarev** [comment]
@lukefan Good point! 

You can either do this:
```ruby
ollama = Langchain::LLM::Ollama.new(url: ENV["OLLAMA_URL"], default_options: { completion_model_name: "mistral" })
ollama.summarize()
```

Or we can add the `model:` param to the `summarize()` method.

What do you think?

**Comment by lukefan** [comment]
Thanks. I looked at the code today and found that your default model is llama2, and I did not pull this model.

**Comment by andreibondarev** [comment]
> Thanks. I looked at the code today and found that your default model is llama2, and I did not pull this model.

I'll switch to llama3, there's no reason not to.

**Comment by lukefan** [comment]
llama3 is better.
but, I'm Chinese. So my default model is Llama3-8B-Chinese-Chat and qwen:32b-chat.
