### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by mtrefilek** [patterns-ai-core/langchainrb#584]
Hi @andreibondarev, how do you handle releases for these repos? I notice you use PRs to bump versions and changelog. Are you okay with others submitting a version bump PR for discussion, or are you following a cadence?

Thanks for all your great work!

**Comment by andreibondarev** [comment]
@mtrefilek I'm okay if you'd like to push out `0.11.4` out.
1. Bump the version up
2. `bundle install`
3. Write up a CHANGELOG
4. Open a PR against `main`

I usually push a new version out whenever it "feels" like there's a good amount of new changes that warrants a new release.

**Comment by mtrefilek** [comment]
@andreibondarev Thank you!!
