### ISSUE TITLE
OpenAI can't get default_dimensions, when I specify a special embedding_model.

### ISSUE THREAD

**Issue by lukefan** [patterns-ai-core/langchainrb#598]
Many services are now compatible with the OpenAI API, including Ollama. 
So when I use OpenAI as a large model, I hope to specify a special embedding_model. 
You can refer to the method used in Ollama and directly do a simple embedding to confirm the length of the vector output by the current embedding model.
just like: lib/langchain/llm/ollama.rb

**Comment by andreibondarev** [comment]
@lukefan Could you please show me the code and the error you're seeing?

**Comment by lukefan** [comment]
config/initializers/langchainrb_rails.rb:
`
LangchainrbRails.configure do |config|
  config.vectorsearch = Langchain::Vectorsearch::Pgvector.new(
    llm: Langchain::LLM::OpenAI.new(
      api_key: 'ollama',
      llm_options: {uri_base:'http://localhost:11434'},
      default_options: {
        embeddings_model_name: 'chevalblanc/dmeta-embedding-zh:latest',
        n: 1,
        temperature: 0.8,
        chat_completion_model_name: 'Llama3-8B-Chinese-Chat:latest',
        },
      )
  )
end
`
so I got this error:
key not found: "chevalblanc/dmeta-embedding-zh:latest"

**Comment by andreibondarev** [comment]
@lukefan I don't see this model on Ollama: https://ollama.com/search?q=chevalblanc&p=1

**Comment by andreibondarev** [comment]
But if you wanted to use `chevalblanc/embedding` model for example. Make sure you've pulled the model down:
```bash
ollama pull chevalblanc/embedding
pulling manifest
pulling 7c43e3a2e21a... 100% ▕███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ 651 MB
pulling 4964a5df96b1... 100% ▕███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  260 B
verifying sha256 digest
writing manifest
removing any unused layers
success
```
and then use the Ollama LLM:
```ruby
llm = Langchain::LLM::Ollama.new(url: ENV["OLLAMA_URL"], default_options: { embeddings_model_name: "chevalblanc/embedding"})

llm.embed text: "..."
=>
#<Langchain::LLM::OllamaResponse:0x00000001253740d0
 @model="chevalblanc/embedding",
 @prompt_tokens=nil,
 @raw_response=
  {"embedding"=>
    [-0.40095722675323486,
     -0.019067473709583282,
     -0.2779462933540344,
     ...
```

**Comment by lukefan** [comment]
https://ollama.com/milkey/dmeta-embedding-zh
they change url.

**Comment by andreibondarev** [comment]
@lukefan Then...
```bash
ollama pull milkey/dmeta-embedding-zh:f16 # of :f32
```
```ruby
llm = Langchain::LLM::Ollama.new(url: ENV["OLLAMA_URL"], default_options: { embeddings_model_name: "milkey/dmeta-embedding-zh:f16"})
```

**Comment by lukefan** [comment]
I want to be able to use OpenAI to call various compatible services, not just ollama.

**Comment by lukefan** [comment]
I don't expect to use OpenAI's API to call all services. But I will try to choose services that are compatible with OpenAI. So I hope that OpenAI's support can consider compatibility more.

**Comment by lukefan** [comment]
@andreibondarev Sorry.
There is a problem with my test. ollama does not implement embeddings compatible with OpenAI.
However, Together does implement this part of the functionality. I should use the embeddings of together.xyz for testing.

**Comment by andreibondarev** [comment]
@lukefan Right, the embeddings are different. Should we close this issue now?

**Comment by andreibondarev** [comment]
@lukefan I think we can probably remove this max token validation: https://github.com/patterns-ai-core/langchainrb/blob/main/lib/langchain/llm/openai.rb#L76

**Comment by lukefan** [comment]
Yes, this should solve the problem better.
