### ISSUE TITLE
Running into issue running migrations

### ISSUE THREAD

**Issue by jeperkins4** [patterns-ai-core/langchainrb#638]
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `default_dimensions' for #<Langchain::LLM::OpenAI:...

Anyone else come across this issue?

**Comment by andreibondarev** [comment]
@jeperkins4 Are you using `langchainrb` or `langchainrb_rails` gem?

**Comment by andreibondarev** [comment]
@jeperkins4 Can you show the full error stack? Which version of the gem are you using?

**Comment by jeperkins4** [comment]
Sorry... I should have posted this under the langchainrb_rails.  Let me close this and repost w/ full stack over there.

**Comment by jeperkins4** [comment]
Wrong gem
