### ISSUE TITLE
Google Gemini LLM generation config problem

### ISSUE THREAD

**Issue by mazenkhalil** [patterns-ai-core/langchainrb#648]
The following line in Google Gemini LLM seems to be wrong.
If the `temperature` is defined, the whole `generation_config` object gets replaced thus ignoring any pre defined parameters there!

https://github.com/patterns-ai-core/langchainrb/blob/0efc39269e5c2c123886fa34e10b28c682ada948/lib/langchain/llm/google_gemini.rb#L45

**Comment by andreibondarev** [comment]
@mazenkhalil Do you have a suggested fix?

I think we should set the [possible values](https://ai.google.dev/api/rest/v1/GenerationConfig) directly, something like the following:
```ruby
parameters[:generation_config] ||= {}
parameters[:generation_config].merge({temperature: parameters.delete(:temperature)}) if parameters[:temperature]
parameters[:generation_config].merge({top_k: parameters.delete(:top_k)}) if parameters[:top_k]
...
```
