### ISSUE TITLE
Stream response from the Langchain Assistant

### ISSUE THREAD

**Issue by andreibondarev** [patterns-ai-core/langchainrb#684]
WIP

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mengqing** [comment]
I tested this [PR](https://github.com/patterns-ai-core/langchainrb/pull/484) in my own project and it actually works as expected

**Comment by andreibondarev** [comment]
Closing this PR since https://github.com/patterns-ai-core/langchainrb/pull/760 was merged.
