### ISSUE TITLE
Example for Assistants with Files uploaded into threads

### ISSUE THREAD

**Issue by ausangshukla** [patterns-ai-core/langchainrb#685]
How can I use an assistant where I upload some documents that the assistant has access to when asked a question?
If there is a better forum to ask the question in, pl lmk.

Regards

**Comment by andreibondarev** [comment]
I assume you'd like the Assistant to perform RAG? If so:
1. You'd have to manually upload documents to a vectorstore database, let's say Chroma:
```ruby
chroma = Langchain::Vectorsearch::Chroma.new(url:, index_name:, llm:, api_key: nil)

doc1 = Langchain.root.join("path/to/my.pdf")
doc2 = Langchain.root.join("path/to/my.txt")
doc3 = Langchain.root.join("path/to/my.docx")

client.add_data(paths: [doc1, doc2, doc3])
```

2. Instantiate an Assistant and expose it as a tool:
```ruby
vectorsearch_tool = Langchain::Tool::Vectorsearch.new(vectorsearch: chroma)

assistant = Langchain::Assistant.new(
  llm: llm,
  tools: [vectorsearch_tool]
```

When you run queries now, the Assistant should be retrieving docs from a vectorsearch DB:
```ruby
assistant.add_message_and_run(content: "...", auto_tool_execution: true)
```

**Comment by ausangshukla** [comment]
I would like to send the whole document, and not snippets, this is cause I want to have a conversation with one specific doc. This use to be possible in older versions of this gem which is not working now, see old code which use to work below

files = OpenAI::Files.new(client:)
uploaded_file = files.upload(parameters: { file: tmp_file.path, purpose: "assistants" })

**Comment by ausangshukla** [comment]
In the older version of the code, I could pass the following to an assistant. 
tools: [
            { type: 'retrieval' }, # Allow access to files attached using file_ids
            { type: 'code_interpreter' } # Allow access to Python code interpreter
],

Now however the new api only takes Langchain::Tool array. How to proceed?

**Comment by andreibondarev** [comment]
> In the older version of the code, I could pass the following to an assistant. tools: [ { type: 'retrieval' }, # Allow access to files attached using file_ids { type: 'code_interpreter' } # Allow access to Python code interpreter ],
> 
> Now however the new api only takes Langchain::Tool array. How to proceed?

The `Langchain::Assistant` class is not a wrapper on top of the OpenAI Assistants API, it's a wrapper on top of any LLM chat completions endpoint that supports Function Calling.

**Comment by ausangshukla** [comment]
But then how can my assistants access the code interpreter within GPT or the files uploaded to GPT? Sorry for the questions.

**Comment by andreibondarev** [comment]
@ausangshukla Do you have a hard requirement to use the Python code interpreter or would the RubyCodeInterpreter Tool work for you?

**Comment by ausangshukla** [comment]
Well the thing is I want to submit an entire XL sheet, as questions of GPT and then get it to give me the ans, which may include using pandas to analyze the docs. So thats the use case, I want to GPT to use its code interpreter, not run code on my machine using ruby.

**Comment by andreibondarev** [comment]
@ausangshukla You can use the OpenAI Assistants API directly of course. Alternatively -- this gem gives you more control: picking any LLM, any vectorsearch storage, parsing your own data, etc.

**Comment by andreibondarev** [comment]
> Well the thing is I want to submit an entire XL sheet, as questions of GPT and then get it to give me the ans, which may include using pandas to analyze the docs. So thats the use case, I want to GPT to use its code interpreter, not run code on my machine using ruby.

You could also use https://github.com/ankane/ruby-polars if you'd like to stay in the Ruby ecosystem.

**Comment by ausangshukla** [comment]
Is there a sample of using Ruby Polars as a tool within langchain.rb ? Something like PandasAi ?

**Comment by andreibondarev** [comment]
@ausangshukla Could you please email me with more info about your use-case? I'll see if I can help!
