### ISSUE TITLE
License problem due to using "colorize" gem that is licensed under GPL

### ISSUE THREAD

**Issue by Azdaroth** [patterns-ai-core/langchainrb#726]
Thanks for building this amazing gem!

I was planning to use it in one of the apps, however, the _license finder_ reported a severe issue: the gem is dependent on `colorize` which is licensed under GPL-2 (https://github.com/fazibear/colorize/blob/master/LICENSE) which creates a massive issue since it's a copyleft license. Also that would imply that `langchainrb` itself would need to use GPL-compatible license and MIT would not be an option.

Would you consider merging a PR that replaces `colorize` with something that has a friendlier license, e.g. `rainbow` gem? I would be happy to submit it.

**Comment by andreibondarev** [comment]
@Azdaroth Thank you for flagging, I was definitely unaware of this. I'd be happy accept a PR switching to `rainbow` if you'd like to put it together. Thank you!
