### ISSUE TITLE
LLM::Azure doesn't update all chat_parameters fields

### ISSUE THREAD

**Issue by namiwang** [patterns-ai-core/langchainrb#740]
In `LLM::OpenAI`'s `initialize`:

```
@defaults = DEFAULTS.merge(default_options)
chat_parameters.update(
  model: {default: @defaults[:chat_completion_model_name]},
  logprobs: {},
  top_logprobs: {},
  n: {default: @defaults[:n]},
  temperature: {default: @defaults[:temperature]},
  user: {}
)
```

However, in `LLM::Azure`'s initializer, only following fields are getting updated

```
@defaults = DEFAULTS.merge(default_options)
chat_parameters.update(
  logprobs: {},
  top_logprobs: {},
  user: {}
)
```

This means that the following code is not working

```
@llm = Langchain::LLM::Azure.new(
  api_key: 'key',
  llm_options: {
    api_type: :azure,
    uri_base: 'uri',
    api_version: "2023-03-15-preview",
  },
  default_options: {
    chat_completion_model_name: "gpt-4o",
  }
)
```

with error `model argument is required (ArgumentError)` error since `parameters[:model]` is empty.

As a workaround, I have to manually do `@llm.chat_parameters.update(model: {default: @llm.defaults[:chat_completion_model_name]},)` afterwards.

I'm happy to help fix this if it's indeed unexpected behavior.

**Comment by andreibondarev** [comment]
@namiwang Very open to any help with a PR here!

**Comment by namiwang** [comment]
@andreibondarev there it is
