### ISSUE TITLE
Option to Disable Logging

### ISSUE THREAD

**Issue by bendangelo** [patterns-ai-core/langchainrb#750]
**Is your feature request related to a problem? Please describe.**
Disable logging for when running the test suite etc.

**Describe the solution you'd like**
`  Langchain.logger.level = :warn` could disable farday logging.

**Describe alternatives you've considered**

**Additional context**

**Comment by andreibondarev** [comment]
@bendangelo What're your thoughts of dropping:
```ruby
Langchain.logger.level = :warn
```
somewhere in the `spec_helper.rb`?

**Comment by bendangelo** [comment]
I should have mentioned the logs are coming from faraday. Changing that log level doesn't stop faraday from logging things.

**Comment by bendangelo** [comment]
I'm still waiting on a response.

**Comment by cgimenez** [comment]
For lack of a better solution, I just commented out the offending line in the installed gem...

**Comment by andreibondarev** [comment]
I'm looking into this right now...

**Comment by andreibondarev** [comment]
I'm rolling out a fix but I'd like to overhaul the whole logger solution over the long term.

If you set:
```ruby
Langchain.logger.level = :error`
```
you should not be seeing anything from Ollama unless it errors.
