### ISSUE TITLE
Replicate LLM provider configuration broken?

### ISSUE THREAD

**Issue by tamaloa** [patterns-ai-core/langchainrb#795]
When trying to use the LLM::Replicate provider the configuration is broken.

Using the **current** langchainrb and replicate-ruby gems and following the Instruction given in the documentation:

```
Langchain::LLM::Replicate.new(api_key: ENV["REPLICATE_API_KEY"])
NoMethodError: undefined method `configure' for Replicate:Class
from .../gems/ruby-3.2.5/gems/langchainrb-0.16.0/lib/langchain/llm/replicate.rb:38:in `initialize'
```

```
bundle info langchainrb --version               
# 0.16.0
bundle info replicate-ruby --version
# 0.2.3
```
`

I checked the **old langchainrb version** for which Replicate Support was initally released (#23) and got the same failure

Gemfile for langchain version 0.3.10 and specific replicate-ruby fork as indicated by README
```
gem "langchainrb", "= 0.3.10"
gem "replicate-ruby", git: "https://github.com/andreibondarev/replicate-ruby.git", branch: "faraday-1.x"
```

```
require 'langchain'
LLM::Replicate.new(api_key: ENV["REPLICATE_API_KEY"])
# NoMethodError: undefined method `configure' for Replicate:Class
# from ../gems/ruby-3.2.5/gems/langchainrb-0.3.10/lib/llm/replicate.rb:32:in `initialize'
```

As even the old version does not configure I assume I am missing something important?

(Note: I am and have been using LLM::Ollama successfully so in general my setup seems to function)

**Comment by tamaloa** [comment]
Turns out the project at hand already contained another `Replicate` class which of course breaks calling replicate-ruby's classes :)

**Comment by andreibondarev** [comment]
> Turns out the project at hand already contained another `Replicate` class which of course breaks calling replicate-ruby's classes :)

@tamaloa Did you end up renaming the class in your project?

Over the long-term I'd like to drop a lot of these 3rd party gem dependencies and keep it all in this gem.

**Comment by tamaloa** [comment]
Yes it was possible (currently only working on a spike) and it worked then. But I am now calling the Replicate API directly.

I do also think it would be sensible to drop 3rd party gems which do not really offer any real advantage over calling the API directly. But i also see how it must be a huge effort to keep all those integration up-to-date.

Maybe you could only integrate one or two provders directly and provide an interface for interested third parties to provide gems (which then do exactly what's necessary to fully support langchainrbs capabilities).
