### ISSUE TITLE
Add ability to send images to the Assistant when using Anthropic

### ISSUE THREAD

**Issue by andreibondarev** [patterns-ai-core/langchainrb#848]
## Description

When using the `Langchain::Assistant`, with Anthropic, we'd like to be able to send an image URLs to the LLM.
Ollama docs: https://docs.anthropic.com/en/api/messages.

We should be able to do the following:
```ruby
llm = Langchain::LLM::Anthropic.new(api_key: ENV["ANTHROPIC_API_KEY"])

assistant = Langchain::Assistant.new(llm: llm)

assistant.add_message_and_run(
  image_url: "https://gist.githubusercontent.com/andreibondarev/b6f444194d0ee7ab7302a4d83184e53e/raw/099e10af2d84638211e25866f71afa7308226365/sf-cable-car.jpg",
  content: "Please describe this image"
)
#=> LLM successfully responds.
```

Since Ollama only accepts base64-encoded images, we should download the image into memory and then convert to its Base64 format.

Sample code that I've prototyped:
```ruby
require 'open-uri'
require 'base64'

def image_url_to_base64(url)
  # Download the image
  image_data = URI.open(url).read

  # Convert to Base64
  base64_encoded = Base64.strict_encode64(image_data)

  base64_encoded
end

url = "https://gist.githubusercontent.com/andreibondarev/b6f444194d0ee7ab7302a4d83184e53e/raw/099e10af2d84638211e25866f71afa7308226365/sf-cable-car.jpg"
base64_string = image_url_to_base64(url)
```

Tasks:

- [x] Add support for accepting `image_url` and converting it to Base64 [here](https://github.com/patterns-ai-core/langchainrb/blob/main/lib/langchain/assistant/llm/adapters/anthropic.rb#L40-L41).
- [x] Add tests.

**Comment by dferrazm** [comment]
Anthropic docs: https://docs.anthropic.com/en/api/messages
